name: unit-test
run-name: Run unit tests by @${{ github.actor }}
on:
  push:
    branches: [ test-actions ]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    env:
      DISPLAY: ':99.0'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.dev.txt
          sudo apt install -y xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool
          sudo apt-get update
          sudo apt-get install ffmpeg libsm6 libxext6  -y
      - name: Test with pytest
        run: ./tests/test.sh
