name: unit-tests
run-name: Run unit tests after push by @${{ github.actor }}
on:
  push:
    branches: [ test-actions ]
jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os : [ubuntu-latest]
        python-version: [ "3.10" ]
    env:
      DISPLAY: ':99.0'
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install Qt
        uses: tlambert03/setup-qt-libs@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start Xvfb
        run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          Xvfb :99 -ac -screen 0 1024x768x24 & export DISPLAY=:99
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install -y xvfb x11-utils libxkbcommon-x11-0
          sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          pip install wheel
          pip install -r requirements.dev.txt
          pip uninstall opencv-python -y
          pip install opencv-python-headless
          pip install pyside2 pytest coverage pytest-qt
          python -m pip install coverage pytest
          pip install PyQt6
          pip install pytest-xvfb
      - name: Check job values
        run: |
          echo "---- General setup"
          echo "OS:" ${{ matrix.os }}
          echo "PYTHON_VERSION:" ${{ env.PYTHON_VERSION }}
          echo "---- PyQt"
          echo "PYQT_EXTRAS:" ${{ env.PYQT_EXTRAS }}
          echo "---- PyQt5"
          echo "SKIP_PYQT5:" ${{ matrix.skip-pyqt5 }}
          echo "PYQT5_VERSION:" ${{ env.PYQT5_VERSION }}
          echo "PYQT5_QT_VERSION:" ${{ env.PYQT5_QT_VERSION }}
          echo "QSCINTILLA_VERSION:" ${{ env.QSCINTILLA_VERSION }}
          echo "---- PyQt6"
          echo "SKIP_PYQT6:" ${{ matrix.skip-pyqt6 }}
          echo "PYQT6_VERSION:" ${{ env.PYQT6_VERSION }}
          echo "PYQT6_QT_VERSION:" ${{ env.PYQT6_QT_VERSION }}
          echo "---- PySide2"
          echo "SKIP_PYSIDE2:" ${{ matrix.skip-pyside2 }}
          echo "PYSIDE2_VERSION:" ${{ env.PYSIDE2_VERSION }}
          echo "PYSIDE2_QT_VERSION:" ${{ env.PYSIDE2_QT_VERSION }}
          echo "---- PySide6"
          echo "SKIP_PYSIDE6:" ${{ matrix.skip-pyside6 }}
          echo "PYSIDE6_VERSION:" ${{ env.PYSIDE6_VERSION }}
          echo "PYSIDE6_QT_VERSION:" ${{ env.PYSIDE6_QT_VERSION }}
          echo "---- Other"
          echo "SKIP_PIP_CHECK:" ${{ env.SKIP_PIP_CHECK }}
      - name: Test with pytest
        run: |
         xvfb-run --auto-servernum --server-num=1 --server-args="-screen 1 1920x1200x24 -ac +extension GLX" ./tests/test.sh


